Initial development
VeroPruss/Upstay pull request #1
Opened 2021-04-16 12:40 UTC by VeroPruss

2021-04-16 15:37 UTC, YuvalPruss requested changes
CR

2021-04-16 15:37 UTC, YuvalPruss commented on managers/HotelManager.py
> +            raise err
Docs in python are written like this:
```suggestion
    @staticmethod
    def hotel_exists(hotel_id):
        """"
        Check if hotel id exists
        """
        hotel_query = "SELECT hotel_id FROM hotels WHERE hotel_id = {0}" \
            .format(str(hotel_id))
        try:
            return DB.execute_query(hotel_query, QueryType.Single) is not None
        except Error as err:
            raise err
```

2021-04-16 15:37 UTC, YuvalPruss commented on managers/HotelManager.py
> +                                "WHERE hotel_id = {0}".format(str(hotel_id))
Even better:
```suggestion
            hotel_rooms_query = f"SELECT hotel_id, room_type, amount_of_rooms FROM hotel_rooms " \
                                "WHERE hotel_id = {str(hotel_id)}"
```

2021-04-16 15:37 UTC, YuvalPruss commented on managers/ReservationManager.py
> +        reserved_rooms_query = "SELECT COUNT(*) FROM reservations " \
Same comment with the f-string, but LGTM

2021-04-16 15:37 UTC, YuvalPruss commented on models/HotelRoom.py
> +    def __init__(self, hotel_id, room_type, total_amount_of_rooms):
Dataclass - no need for initialized :-)

2021-04-16 15:37 UTC, YuvalPruss commented on models/HotelRoomInventory.py
> +    def __init__(self, hotel_room, amount_of_reservations):
Dataclass - no need for initialized :-)

2021-04-16 15:37 UTC, YuvalPruss commented on models/Reservation.py
> +    def __init__(self, reservation_id, hotel_id, room_type, arrival_date, departure_date, status):
Dataclass - no need for initialized :-)

2021-04-16 15:37 UTC, YuvalPruss commented on app.py
> +    return json(ApplicationManager.cancel_reservation(reservation_id))
Use the `asdict` instead of implementing in each return statement

2021-04-16 15:37 UTC, YuvalPruss commented on app.py
> +    return json(ApplicationManager.get_reservation_by_id(reservation_id))
Use the asdict instead of implementing in each return statement

2021-04-16 15:37 UTC, YuvalPruss commented on managers/ReservationManager.py
> +    def create_reservation(hotel_id, room_type, date_from, date_to):
Same note about the `asdict`

2021-04-16 15:37 UTC, YuvalPruss commented on managers/ReservationManager.py
> +                                       "values ({0}, {1}, '{2}', '{3}', {4}) " \
LGTM, but pay attention it may cause a KeyError :-) Maybe you can catch it and return an appropriate message "You're missing the ____ param"

2021-04-16 15:37 UTC, YuvalPruss commented on managers/ApplicationManager.py
> +            raise err
No point to catch the error only to raise it gain, you can omit this

2021-04-16 15:37 UTC, YuvalPruss commented on generals/SQLHandler.py
> +                result_set = cursor.fetchone()
If it's returning the same type - it's very good.
If not - Let's be safe and separate them to different methods

2021-04-16 15:37 UTC, YuvalPruss commented on generals/SQLHandler.py
> +                print("error closing connection")
Maybe better to log it instead of print it :-)

2021-04-16 15:37 UTC, YuvalPruss commented on generals/DB_Settings.py
> +DB_PARMS = {"DB_NAME": "upstay2",
Not the safe approach although on this scale it's ok
just for your knowledge, better use it as an environment variable

2021-04-16 15:37 UTC, YuvalPruss commented on .idea/UpstayBE.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Remove this and the .pyc files from the git.
Add a .gitignore and include those suffixes
For more info - https://stackoverflow.com/questions/27850222/what-is-gitignore-exactly/27850270

2021-04-17 20:21 UTC, VeroPruss commented on generals/Message.py
> +    def __init__(self, msg_type, msg_text):
removed the __init__ function in all dataclasses

2021-04-17 20:23 UTC, VeroPruss commented on generals/QueryType.py
> +import enum
done

2021-04-17 20:37 UTC, VeroPruss commented on managers/HotelManager.py
> +            raise err
fixed

2021-04-17 20:43 UTC, VeroPruss commented on managers/HotelManager.py
> +                                "WHERE hotel_id = {0}".format(str(hotel_id))
fixed all sql statements in code

2021-04-17 20:43 UTC, VeroPruss commented on managers/ReservationManager.py
> +        reserved_rooms_query = "SELECT COUNT(*) FROM reservations " \
fixed.

2021-04-17 20:43 UTC, VeroPruss commented on models/HotelRoom.py
> +    def __init__(self, hotel_id, room_type, total_amount_of_rooms):
V

2021-04-17 20:43 UTC, VeroPruss commented on models/HotelRoomInventory.py
> +    def __init__(self, hotel_room, amount_of_reservations):
V

2021-04-17 20:43 UTC, VeroPruss commented on models/Reservation.py
> +    def __init__(self, reservation_id, hotel_id, room_type, arrival_date, departure_date, status):
V

2021-04-18 21:10 UTC, VeroPruss commented on generals/SQLHandler.py
> +                result_set = cursor.fetchone()
They both return result set, supposed to be safe...

2021-04-18 21:10 UTC, VeroPruss commented on managers/ApplicationManager.py
> +            raise err
fixed.

2021-04-18 21:10 UTC, VeroPruss commented on managers/ApplicationManager.py
> +            raise err
fixed

2021-04-20 17:51 UTC, VeroPruss commented on .idea/UpstayBE.iml
> +<?xml version="1.0" encoding="UTF-8"?>
DONE!!

2021-04-20 18:04 UTC, VeroPruss commented on generals/DB_Settings.py
> +DB_PARMS = {"DB_NAME": "upstay2",
I added .env file and all important parametes are now in this file and would not be visible where they should not be!

2021-04-20 18:21 UTC, VeroPruss commented on generals/SQLHandler.py
> +                print("error closing connection")
I removed the print statement, it raises an error anyway..

2021-04-24 14:47 UTC, VeroPruss commented on managers/ReservationManager.py
> +                                       "values ({0}, {1}, '{2}', '{3}', {4}) " \
not relevant.

2021-04-24 15:29 UTC, merged